# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-09-09 07:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='updated',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2019, 9, 9, 7, 9, 16, 418678, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
